mapping_method: count_mapping   # 选择建图方法，目前支持：覆盖栅格建图(cover_grid)、计数建图(count_mapping)

# 地图参数配置
gridmap_width: 2000
gridmap_height: 2000
gridmap_resolution: 0.05

gridmap_log_free: -2
gridmap_log_occ: 1
gridmap_log_max: 100.0
gridmap_log_min: 0.0

gridmap_origin_x: -50
gridmap_origin_y: -50
gridmap_offset_x: 0
gridmap_offset_y: 0